### ISSUE TITLE
Change snowflake to name space package

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/snowflake-ingest-python#19]
See https://github.com/snowflakedb/snowflake-connector-python/blob/master/setup.py#L54

As a result, __init__.py should be removed from this:
https://github.com/snowflakedb/snowflake-ingest-python/tree/master/snowflake

The idea is by having a name space package, we can easily share the directory among all snowflake packages.

**Comment by howryu** [comment]
I tried installing both snowflake-connector-python and snowflake-ingest-python in my virtual environment. And I can see both packages under same namespace (`python34-env/lib/python3.4/site-packages/snowflake/ingest` and `python34-env/lib/python3.4/site-packages/snowflake/connector`) I don't understand why removing `__init__.py` make any difference.

**Comment by smtakeda** [comment]
hmm, sorry I took wrong for __init__.py. As long as __init__.py is not copied to `lib/python3.5/site-packages/snowflake`, it should be good. I just don't get why __init__.py is in the source tree. Will investigate further later.
