### ISSUE TITLE
Constantly getting JWT token is invalid despite verifying correct private and Public Token used

### ISSUE THREAD

**Issue by AdrielVelazquez** [snowflakedb/snowflake-ingest-python#21]
I don't have any insight into the error at the moment. 

I suspect I'm neglecting a step that's not indicated in any of the tutorials. 
```
Traceback (most recent call last):
  File "load_pipe.py", line 133, in <module>
    ingest_files(staged_file_list)
  File "load_pipe.py", line 87, in ingest_files
    resp = ingest_manager.ingest_files(staged_file_list)
  File "/usr/local/lib/python3.5/dist-packages/snowflake/ingest/simple_ingest_manager.py", line 121, in ingest_files
    response_body = self.restful.post(target_url, json=payload, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/snowflake/ingest/utils/network.py", line 33, in post
    return self._exec_request_with_retry(url=url, method='POST', json=json, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/snowflake/ingest/utils/network.py", line 83, in _exec_request_with_retry
    raise IngestResponseError(response)
snowflake.ingest.error.IngestResponseError: Http Error: 401, Vender Code: 390144, Message: JWT token is invalid.
```

**Comment by howryu** [comment]
This error message means that your key pair authentication failed.

Can you double check if all steps setup correctly for key pair? Or re-generate the key pair? Note that the private key should be at least 2048 bit in PKCS#8 format. Can you show me the command you used to generate the key pair?

Another suggestion is enable logging, in the log file you should be able to see your JWT(json web token) for authentication. Then you can put your encoded token in https://jwt.io/ to verify that if payload is correct or not.

**Comment by AdrielVelazquez** [comment]
@howryu I'm actually using the script provided on the website

I run through the normal Simple ingest manager for everything else. 
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization

private_key = rsa.generate_private_key(backend=default_backend(),
                                       public_exponent=65537,
                                       key_size=2048)

private_key_in_pem = private_key.private_bytes(encoding=serialization.Encoding.PEM,
                                               format=serialization.PrivateFormat.PKCS8,
                                               encryption_algorithm=serialization.NoEncryption())

public_key = private_key.public_key()
public_key_in_pem = public_key.public_bytes(serialization.Encoding.PEM,
                                            serialization.PublicFormat.SubjectPublicKeyInfo)

with open("private_key.pem", "w") as private_pem:
    private_pem.write(private_key_in_pem.decode())
with open("public_key.pem", "w") as public_pem:
    public_pem.write(public_key_in_pem.decode())

```

**Comment by AdrielVelazquez** [comment]
@howryu Also I should add that I did get signature verified in the jwt.io website

**Comment by howryu** [comment]
Interesting. Can you provide your account name, user name and region? I will try to look into server logs. Also, you have access to the audit log, you might be able to see why it failed.

**Comment by howryu** [comment]
@AdrielVelazquez  Any progress on this issue?

**Comment by AdrielVelazquez** [comment]
@howryu Yup, I opened it a ticket with support to check on the reason. I'll report back once I get a reason.

**Comment by bt-wil** [comment]
I've ran into the same issue. I've test the token decoding on jwt.io and pyjwt using my private/public key and it works, so it was not a token issue.  After a lot of trial and error, I got the solution by pure luck.


```
SimpleIngestManager('acme.us-east-1', 'user', ...).ingest_files(...)
=> Http Error: 401, Vender Code: 390144, Message: JWT token is invalid.

SimpleIngestManager('acme', 'user', ...).ingest_files(...)
=>  Http Error: 403, Message: Forbidden

SimpleIngestManager('acme', 'user', ..., host='acme.us-east-1.snowflakecomputing.com').ingest_files(...)
=> OK!
```

**Comment by tatitati** [comment]
> SimpleIngestManager('acme', 'user', ..., host='acme.us-east-1.snowflakecomputing.com').ingest_files(...)
> => OK!

That didn't work for me. I tried all that, but still I'm having the same issue "jwt token is invalid"
