### ISSUE TITLE
Constantly getting 401 Error despite verifying correct private and Public keys

### ISSUE THREAD

**Issue by Nawter** [snowflakedb/snowflake-ingest-python#29]
I need your help my friend I tried many things and don't working anything, I have connection with the snowflake using snowsql but never have a connection using your python Library.
Cheers
```
Traceback (most recent call last):
  File "simple_ingest_snowflake.py", line 48, in <module>
    resp = ingest_manager.ingest_files(staged_files)
  File "/Users/almalikz/anaconda3/lib/python3.7/site-packages/snowflake/ingest/simple_ingest_manager.py", line 121, in ingest_files
    response_body = self.restful.post(target_url, json=payload, headers=headers)
  File "/Users/almalikz/anaconda3/lib/python3.7/site-packages/snowflake/ingest/utils/network.py", line 33, in post
    return self._exec_request_with_retry(url=url, method='POST', json=json, headers=headers)
  File "/Users/almalikz/anaconda3/lib/python3.7/site-packages/snowflake/ingest/utils/network.py", line 83, in _exec_request_with_retry
    raise IngestResponseError(response)
snowflake.ingest.error.IngestResponseError: Http Error: 401, Vender Code: 390100, Message: Incorrect username or password was specified.
```

**Comment by Nawter** [comment]
I got the same error using the rest api generate the JWT by myself using this two files https://github.com/snowflakedb/snowflake-ingest-python/blob/master/snowflake/ingest/utils/tokentools.py
and
https://github.com/snowflakedb/snowflake-ingest-python/blob/master/snowflake/ingest/simple_ingest_manager.py

**Comment by howryu** [comment]
Can you provide a little more detail, this is really hard to debug. request id? Which deployment are you running against? Is there any log files?

**Comment by Nawter** [comment]
Hi Howryu,
Thank you for your response,
account='by16910.eu-west-1',
host='by16910.eu-west-1.snowflakecomputing.com',
user:ALMALIKZ
Tomorrow I will bring you the code, the request id and logs.

**Comment by howryu** [comment]
Can you change the account parameter to be `by16910`?

**Comment by Nawter** [comment]
Thank you my friend @howryu is working now, have a nice day.
