### ISSUE TITLE
Version of the requests package specified in the dependencies

### ISSUE THREAD

**Issue by fvaleye** [snowflakedb/snowflake-ingest-python#59]
Could you explain why the version of the `requests` package is required with `<2.24.0` in the dependencies?
https://github.com/snowflakedb/snowflake-ingest-python/blob/master/setup.py#L16

When using multiple versions of the `requests` package, it will be better to use `requests>=2.24.0` in order to avoid dependencies conflicts.

**Comment by sfc-gh-xhuang** [comment]
fixed in https://github.com/snowflakedb/snowflake-ingest-python/pull/73

**Comment by RSiferd2** [comment]
I think the string proposed by @optroodt was to ensure future compatibility with `2.*` of requests.
