### ISSUE TITLE
Please upgrade for modern python versions

### ISSUE THREAD

**Issue by jskrzypek** [snowflakedb/snowflake-ingest-python#63]
Can you please provide a version (ideally via a major version bump) with upgraded dependencies? 
PyJWT < 2 is absurdly old and untenable for modern python environments.
As it stands I will need to rely on a fork.

**Comment by jskrzypek** [comment]
BTW if it helps, the reasoning behind why you pinned the PyJWT version (i.e. #45 by @sfc-gh-jliang) is that you were getting an error, but if you look at the PyJWT changelog, [version 2.0.0 introduced a breaking change that modifies the return type to `string` from `bytes`](https://pyjwt.readthedocs.io/en/stable/changelog.html#jwt-encode-return-type).

The appropriate thing to do when publishing an open source SDK in an open source ecosystem (assuming you want engineers to actually use your product) is to *maintain* the package and update it in response to newer versions of dependencies. To do otherwise invites security issues and frustration among your customers. As it stands, I'm currently advocating to the rest of the Engineering team that we drop snowflake and pick up an alternative if this doesn't get addressed in the next week.

**Comment by jskrzypek** [comment]
Pinging a few more contributors: @howryu @sfc-gh-japatel @sfc-gh-jfan

**Comment by cvlong** [comment]
Adding +1 that this will be a huge improvement to this kit

**Comment by jskrzypek** [comment]
@sfc-gh-jfan You're the last Snowflake engineer to touch this repo. Can we **_please_** get a response here? Should I just push a version 2 of snowflake-ingest to pypi myself? Because that's what the lack of response here is telling me.

**Comment by sfc-gh-xhuang** [comment]
Hi @jskrzypek 

Sorry for the delay.
I will take a look at https://github.com/snowflakedb/snowflake-ingest-python/pull/65 and discuss with my team on making the upgrade.

**Comment by jskrzypek** [comment]
Fantastic! Thank you!

**Comment by jskrzypek** [comment]
For any followers (e.g. @cvlong @Erik-vdg) I ended up not being able to wait any longer so I did release a temporary fork to pypi: https://pypi.org/project/snowflake-ingest-pyjwt-2/ but with a non-conflicting name and as a pre-release version (`2.0.0a1`)

**Comment by sfc-gh-xhuang** [comment]
I'm working on releasing an official updated version: https://github.com/snowflakedb/snowflake-ingest-python/pull/70
There's a few other things we're adding in but hope to get it done this week.

**Comment by jskrzypek** [comment]
🙌 fantastic to hear

**Comment by sfc-gh-xhuang** [comment]
Fixed in https://github.com/snowflakedb/snowflake-ingest-python/pull/73

Release will occur monday

**Comment by cvlong** [comment]
@sfc-gh-xhuang when will v1.0.5 be released?

**Comment by sfc-gh-xhuang** [comment]
We ran into some release blockers publishing to pypi. I'm working to get that resolved ASAP. 

https://github.com/snowflakedb/snowflake-ingest-python/issues/74
