### ISSUE TITLE
Freeze the snowflake connector dependency

### ISSUE THREAD

**Issue by fvaleye** [snowflakedb/snowflake-ingest-python#68]
Using snowflake-ingest-python in our applications, we observed that we download the latest version of the snowflake-python-connector by default as a transversal dependency defined [here](https://github.com/snowflakedb/snowflake-ingest-python/blob/master/setup.py#L13).

The best practice to put in place would be to restrict to a range of known compatible versions (as accurate as possible) for the connector.

**Comment by sfc-gh-xhuang** [comment]
fixed in https://github.com/snowflakedb/snowflake-ingest-python/pull/73
