### ISSUE TITLE
Release date of version 1.0.5 to pypi?

### ISSUE THREAD

**Issue by peter-wimsey** [snowflakedb/snowflake-ingest-python#74]
Hi there,

We are evaluating snowflake-ingest at the moment and while the version from master works fine the latest release 1.0.4 gives us all kind of grief. It pins `pyjwt` and `requests` to rather old versions that don't play well with other libraries.

In some situations installing directly from git's master branch works but in others (like creating a package for an AWS Lambda function using AWS' own tooling) it does not.

Do you have an estimate for the date of the next release?

Thanks

**Comment by sfc-gh-xhuang** [comment]
Hi sorry about the delay, we're actively working on publishing 1.0.5 to pypi, there's been a few blockers but we're hoping to get it resolved and released soon

**Comment by sfc-gh-xhuang** [comment]
Just got it released now
