### ISSUE TITLE
Error handling makes unreliable assumptions about the structure of the payload

### ISSUE THREAD

**Issue by mark-oppenheim** [snowflakedb/snowflake-ingest-python#92]
Verion: 1.0.7
Python: 3.11

Last night (around 2024-08-20 01:23 UTC) the ingestion REST API entered a state where it was returning error responses to all requests.  Our code use the ingest library to communicate with the API. Unfortunately the logs only showed the following stack traces:
```
...our code...
  File "/opt/python/snowflake/ingest/utils/network.py", line 34, in post
    return self._exec_request_with_retry(url=url, method='POST', json=json, headers=headers)
  File "/opt/python/snowflake/ingest/utils/network.py", line 84, in _exec_request_with_retry
    raise IngestResponseError(response)
  File "/opt/python/snowflake/ingest/error.py", line 19, in __init__
    self.success = json_body[u'success']
KeyError: 'success'
```

The code in `snowflake/ingest/error.py` first parses the payload as JSON and then, if parsed successfully, assumes that the payload will contain `code`, `success`, `message` and `data` fields.

```python
        self.code = json_body[u'code']
        self.success = json_body[u'success']
        self._raw_message = json_body[u'message']
        self.data = json_body[u'data']
```

If the payload is missing any of these than a KeyError is reported with no details of the HTTP error. In this morning's case there appears to have been a `code` but no `success` field. To my eye, the code should probably be using `.get(field)` in place of `[field]` - i.e. default to `None` if the field is missing, or move these lines into the previous `try` block (and expand the catch to include `KeyError`).  Whatever the code change, it should ideally log the http error code and the whole of the payload whatever the results of the parsing.

**Comment by sfc-gh-xhuang** [comment]
Thanks for reporting the 2 recent issues @mark-oppenheim. 
Feel free to contribute to the repo if you would like recognition

**Comment by mark-oppenheim** [comment]
> Thanks for reporting the 2 recent issues @mark-oppenheim. Feel free to contribute to the repo if you would like recognition for the suggestions

Will create a PR for this one as soon as I get time.  Thanks for raising the PR for the more urgent one!

**Comment by mark-oppenheim** [comment]
@sfc-gh-xhuang just writing a patch for this but am unsure how to run the tests for this repo locally as `conftest.py` requires `parameters.py.gpg` to have already been decrypted using a secret passphrase.  Am I missing something here, or do I have to just push/PR and rely on the tests running on the server?

**Comment by sfc-gh-xhuang** [comment]
Yes unfortunately you cannot run the tests. Once you have a PR open, I'll send a CLA over and then someone on Snowflake can review and merge the PR for you

**Comment by mark-oppenheim** [comment]
@sfc-gh-xhuang it seems that a PR created by me doesn't have the ability to access the key to decrypt the file either.  See errors in https://github.com/snowflakedb/snowflake-ingest-python/pull/95 :-(
