### ISSUE TITLE
"BEARER" token should be "Bearer" (RFC-6750)

### ISSUE THREAD

**Issue by mark-oppenheim** [snowflakedb/snowflake-ingest-python#93]
The OAUTH "Bearer" header is case sensitive according to RFC-6750.  According to a Snowflake support rep, on 2024-08-20 the Ingestion API attempted to enforce this and had to be rolled back due to failed connection attempts.  This library sends the header as "BEARER" (all upper case).  It would appear that to fix this line 41 of `simple_ingest_manager.py` should be changed from:

```python
BEARER_FORMAT = "BEARER {0}"  # The format of this bearer
```
to
```python
BEARER_FORMAT = "Bearer {0}"  # The format of this bearer
```

**Comment by sfc-gh-xhuang** [comment]
Thanks! I have opened a PR to resolve this

**Comment by mark-oppenheim** [comment]
Thanks @sfc-gh-xhuang
